test: testrestart

testrestart:
	../charmrun +p 4 ++local ../ChaNGa eqHalo.param

clean:
	rm -rf halo.000* 
	rm -rf halo.chk0
	rm -rf halo.chk1
	rm -rf halo.log
	rm -rf halo.timings
	rm -rf lastcheckpoint
	