classic: 
	../charmrun +p4 ++local ../ChaNGa eqHalo.param
socket_test:
	../charmrun ++oneWthPerSocket ++local ../ChaNGa eqHalo.param
auto_test:
	../charmrun ++auto-provision ++local ../ChaNGa eqHalo.param
perpu_test:
	../charmrun ++oneWthPerPU ++local ../ChaNGa eqHalo.param
new3:
	../charmrun 
clean:
	rm -rf halo2.log
	rm -rf halo2.000*
	rm -rf *.ppm
