bothL: defaultL expL
	
defaultL:
	../../charmrun +p4 ++local ../../ChaNGa eqHalo1.param
expL:
	../../charmrun +p4 ++local ../../ChaNGa eqHalo2.param
clean:
	rm -rf *.log *.timings *.000* *.chk* lastcheckpoint
